"use client";

import { useEffect, useMemo, useState } from "react";
import "./war-room.css";

type Meeting = { date:string; label:string; rate:number; actual:number; inflation:number; core:number; unemployment:number; expectations:number; output:number; stress:number; released:string; note:string };
type Decision = { date:string; change:number; guidance:string; memo:string; resultingRate:number; loss:number };

const meetings: Meeting[] = [
  {date:"2022-03-16",label:"16 MAR 2022",rate:.125,actual:.375,inflation:7.9,core:6.4,unemployment:3.8,expectations:2.9,output:1.2,stress:.22,released:"2022-03-10",note:"Energy prices are accelerating after Russia's invasion of Ukraine. Labour demand remains exceptionally strong."},
  {date:"2022-05-04",label:"04 MAY 2022",rate:.375,actual:.875,inflation:8.5,core:6.5,unemployment:3.6,expectations:3.0,output:.6,stress:.27,released:"2022-04-12",note:"Price pressure is broadening. The first estimate of Q1 real GDP has contracted, while final demand remains firm."},
  {date:"2022-06-15",label:"15 JUN 2022",rate:.875,actual:1.625,inflation:8.6,core:6.0,unemployment:3.6,expectations:3.3,output:.25,stress:.34,released:"2022-06-10",note:"The latest CPI release surprised to the upside. Market-based inflation compensation has moved higher."},
  {date:"2022-07-27",label:"27 JUL 2022",rate:1.625,actual:2.375,inflation:9.1,core:5.9,unemployment:3.6,expectations:3.0,output:-.35,stress:.39,released:"2022-07-13",note:"Headline inflation has reached a four-decade high. Indicators of production and spending have softened."},
  {date:"2022-09-21",label:"21 SEP 2022",rate:2.375,actual:3.125,inflation:8.3,core:6.3,unemployment:3.7,expectations:2.8,output:-.45,stress:.46,released:"2022-09-13",note:"Core inflation remains persistent. Housing-sensitive financial conditions are tightening rapidly."},
  {date:"2022-11-02",label:"02 NOV 2022",rate:3.125,actual:3.875,inflation:8.2,core:6.6,unemployment:3.5,expectations:2.7,output:-.25,stress:.51,released:"2022-10-13",note:"Inflation is still broad. Cumulative tightening is beginning to constrain interest-sensitive demand."},
  {date:"2022-12-14",label:"14 DEC 2022",rate:3.875,actual:4.375,inflation:7.1,core:6.0,unemployment:3.6,expectations:2.5,output:-.2,stress:.48,released:"2022-12-13",note:"Headline inflation has eased, but services inflation and wage growth remain elevated."}
];
const changes=[-100,-75,-50,-25,0,25,50,75,100];

function mulberry32(seed:number){return()=>{let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function normal(r:()=>number){const u=Math.max(r(),1e-9),v=r();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function simulate(m:Meeting,rate:number,guidance:string,seed:number){
  const r=mulberry32(seed), paths=1000, horizon=8; const inf:number[][]=[],out:number[][]=[],un:number[][]=[];
  const stance=rate-(2+m.expectations); const comm=guidance==="Hawkish"?.12:guidance==="Dovish"?-.10:0;
  for(let p=0;p<paths;p++){let pi=m.inflation,y=m.output,u=m.unemployment,cred=Math.max(.35,1-Math.abs(m.inflation-2)/12);let pp=[],yy=[],uu=[];
    for(let h=0;h<horizon;h++){const delayed=stance*Math.min(1,h/4); const supply=Math.pow(.68,h)*(m.inflation-m.core); const transmission=.10*Math.max(h-2,0)*Math.exp(-Math.max(h-2,0)/6); y=.85*y-.16*delayed-.08*m.stress+normal(r)*.28; pi=.28*2+.66*pi+.06*(2+(m.expectations-2)*(.72-cred*.18))-transmission*stance+.014*y+.12*supply-comm+normal(r)*.32; u=Math.max(2.5,Math.min(12,4+.85*(u-4)-.288*y+.035*delayed+normal(r)*.09)); cred=Math.max(.2,Math.min(1,cred+.02-Math.abs(pi-2)*.003+(guidance==="Hawkish"?.012:0)));pp.push(pi);yy.push(y);uu.push(u)} inf.push(pp);out.push(yy);un.push(uu)}
  const q=(a:number[][],h:number,p:number)=>{const x=a.map(v=>v[h]).sort((a,b)=>a-b);return x[Math.floor((x.length-1)*p)]};
  return Array.from({length:horizon},(_,h)=>({h,pi:q(inf,h,.5),lo:q(inf,h,.1),hi:q(inf,h,.9),y:q(out,h,.5),u:q(un,h,.5)}));
}

function Spark({values,color="#d6ff3f"}:{values:number[];color?:string}){const min=Math.min(...values),max=Math.max(...values),pts=values.map((v,i)=>`${i/(values.length-1)*100},${42-(v-min)/(max-min||1)*34}`).join(" ");return <svg className="spark" viewBox="0 0 100 48" role="img" aria-label="trend chart"><polyline fill="none" stroke={color} strokeWidth="2" points={pts}/></svg>}
function Metric({label,value,unit,delta}:{label:string;value:string;unit:string;delta:string}){return <div className="metric"><div className="metric-top"><span>{label}</span><span className="live">LIVE</span></div><strong>{value}<small>{unit}</small></strong><span className="delta">{delta}</span></div>}

export default function Home(){
 const [screen,setScreen]=useState<"home"|"room"|"results"|"method">("home"); const [step,setStep]=useState(0); const [bp,setBp]=useState(50); const [guidance,setGuidance]=useState("Data-dependent"); const [memo,setMemo]=useState(""); const [decisions,setDecisions]=useState<Decision[]>([]); const [seed]=useState(220316); const [reveal,setReveal]=useState(false);
 useEffect(()=>{const s=localStorage.getItem("ewr-record");if(s)try{setDecisions(JSON.parse(s))}catch{}},[]);
 const m=meetings[Math.min(step,meetings.length-1)]; const currentRate=decisions.length?decisions[decisions.length-1].resultingRate:m.rate; const forecast=useMemo(()=>simulate(m,currentRate+bp/100,guidance,seed+step),[m,currentRate,bp,guidance,seed,step]);
 const commit=()=>{const rate=Math.max(0,currentRate+bp/100),last=forecast[forecast.length-1];const loss=(Math.pow((last.pi-2)/2,2)+.6*Math.pow(last.y/2,2)+.35*Math.pow((last.u-4)/1.5,2));const next=[...decisions,{date:m.date,change:bp,guidance,memo,resultingRate:rate,loss}];setDecisions(next);localStorage.setItem("ewr-record",JSON.stringify(next));setReveal(true);setMemo("")};
 const advance=()=>{setReveal(false);if(step===meetings.length-1)setScreen("results");else{setStep(step+1);setBp(25)}};
 const reset=()=>{setDecisions([]);localStorage.removeItem("ewr-record");setStep(0);setReveal(false)};
 return <main>
  <header className="topbar"><button className="brand" onClick={()=>setScreen("home")}><span>ECONOMIC</span> WAR ROOM</button><nav><button onClick={()=>setScreen("home")}>Scenarios</button><button onClick={()=>setScreen("method")}>Methodology</button><span className="classification">HISTORICAL LAB / v1.0</span></nav></header>
  {screen==="home"&&<section className="landing">
    <div className="eyebrow">A HISTORICAL CENTRAL-BANKING DECISION LABORATORY</div><h1>MONETARY POLICY<br/><em>UNDER FIRE</em></h1><p className="lead">You are the central bank. The data are incomplete. The consequences arrive late. Make the decision first. Let history speak second.</p>
    <button className="primary" onClick={()=>setScreen("room")}>ENTER THE BRIEFING ROOM <span>→</span></button>
    <div className="scenario-grid"><article className="scenario active"><div className="scenario-head"><span>UNITED STATES · FEDERAL RESERVE</span><b>OPERATIONAL</b></div><h2>THE INFLATION SHOCK</h2><p>March—December 2022 · 7 decisions</p><div className="pressure"><span>PRICE PRESSURE</span><i/><i/><i/><i/><i/></div><footer><span>REAL-TIME INFORMATION</span><span>1000 PATHS / DECISION</span></footer></article><article className="scenario"><div className="scenario-head"><span>FEDERAL RESERVE · 2007–09</span><b>RESEARCH</b></div><h2>THE CREDIT FREEZE</h2><p>Financial stress and the lower bound</p><footer><span>M7 PROTOTYPE</span><span>NOT RELEASED</span></footer></article><article className="scenario"><div className="scenario-head"><span>RESERVE BANK OF INDIA · 2022–24</span><b>RESEARCH</b></div><h2>THE IMPORTED SHOCK</h2><p>Inflation, the rupee and global tightening</p><footer><span>VINTAGE GAPS</span><span>NOT RELEASED</span></footer></article></div>
    <div className="doctrine"><span>DOCTRINE 01</span><p>Alternative-policy outcomes are model-generated counterfactuals—not observations and not claims of causal certainty.</p></div>
  </section>}
  {screen==="room"&&<section className="warroom">
   <div className="room-head"><div><div className="eyebrow">FEDERAL OPEN MARKET COMMITTEE · DECISION {step+1}/{meetings.length}</div><h1>{m.label}</h1></div><div className="rate-block"><span>TARGET RANGE MIDPOINT</span><strong>{currentRate.toFixed(3)}<small>%</small></strong></div></div>
   <div className="ticker"><span>INFORMATION CUTOFF <b>{m.date}</b></span><span>LATEST RELEASE <b>{m.released}</b></span><span className="secure">● ANTI-LOOKAHEAD ACTIVE</span><span>SEED <b>{seed+step}</b></span></div>
   <div className="room-grid"><div className="intel"><div className="section-title"><span>01</span> REAL-TIME INTELLIGENCE <small>AS KNOWN ON {m.date}</small></div><div className="metrics"><Metric label="HEADLINE CPI" value={m.inflation.toFixed(1)} unit="% YoY" delta="BLS initial release"/><Metric label="CORE CPI" value={m.core.toFixed(1)} unit="% YoY" delta="Food & energy excluded"/><Metric label="UNEMPLOYMENT" value={m.unemployment.toFixed(1)} unit="%" delta="Seasonally adjusted"/><Metric label="EXP. INFLATION" value={m.expectations.toFixed(1)} unit="%" delta="Market/survey proxy"/></div><div className="brief"><div className="brief-top"><span>STAFF BRIEF / SITUATION</span><span>CONFIDENCE: MODERATE</span></div><p>{m.note}</p></div><div className="chart-panel"><div className="chart-title"><span>INFLATION: OBSERVED → MODEL DISTRIBUTION</span><small>80% SIMULATED INTERVAL</small></div><div className="fan"><div className="fan-y"><span>10%</span><span>6%</span><span>2%</span></div><svg viewBox="0 0 600 190" role="img" aria-label="Inflation forecast fan chart"><line x1="0" y1="152" x2="600" y2="152" stroke="#455044" strokeDasharray="4 4"/><polygon points={forecast.map((v,i)=>`${i*82},${180-v.hi*15}`).join(" ")+" "+forecast.slice().reverse().map((v,i)=>`${(7-i)*82},${180-v.lo*15}`).join(" ")} fill="#d6ff3f22"/><polyline points={forecast.map((v,i)=>`${i*82},${180-v.pi*15}`).join(" ")} fill="none" stroke="#d6ff3f" strokeWidth="3"/></svg></div></div></div>
    <aside className="decision"><div className="section-title"><span>02</span> SET POLICY</div><label>RATE ACTION <small>BASIS POINTS</small></label><div className="bp-grid">{changes.map(x=><button className={bp===x?"selected":""} onClick={()=>setBp(x)} key={x}>{x===0?"HOLD":x>0?`+${x}`:x}</button>)}</div><div className="new-rate"><span>MODELLED TARGET</span><b>{Math.max(0,currentRate+bp/100).toFixed(3)}%</b></div><label>COMMUNICATION STANCE</label><div className="stance">{["Hawkish","Data-dependent","Dovish"].map(x=><button className={guidance===x?"selected":""} onClick={()=>setGuidance(x)} key={x}>{x}</button>)}</div><label htmlFor="memo">GOVERNOR'S MEMO <small>OPTIONAL</small></label><textarea id="memo" value={memo} onChange={e=>setMemo(e.target.value)} placeholder="Record your reasoning before history is revealed…" maxLength={280}/><div className="forecast-mini"><span>8-QUARTER MODEL MEDIAN</span><div><b>{forecast.at(-1)?.pi.toFixed(1)}%</b><small>inflation</small><Spark values={forecast.map(x=>x.pi)}/></div><div><b>{forecast.at(-1)?.u.toFixed(1)}%</b><small>unemployment</small><Spark values={forecast.map(x=>x.u)} color="#e98757"/></div></div><button className="commit" onClick={commit} disabled={reveal}>LOCK DECISION <span>→</span></button><p className="fine">Model-generated, not a forecast. Effects are distributed over time and conditional on calibrated shocks.</p></aside></div>
   {reveal&&<div className="reveal"><div><span>HISTORY SPEAKS</span><h3>The FOMC set the midpoint to {m.actual.toFixed(3)}%</h3><p>Your path: {(currentRate+bp/100).toFixed(3)}%. The difference is a policy experiment—not evidence of what would certainly have happened.</p></div><button onClick={advance}>{step===meetings.length-1?"VIEW GOVERNOR'S RECORD":"ADVANCE TO NEXT MEETING"} →</button></div>}
  </section>}
  {screen==="results"&&<section className="results"><div className="eyebrow">SCENARIO COMPLETE · GOVERNOR'S RECORD</div><h1>THE COST OF EVERY CHOICE</h1><p className="lead">Observed history and your simulated policy experiment are shown separately.</p><div className="result-grid"><div className="record"><div className="section-title"><span>01</span> POLICY PATH</div><div className="path-chart">{meetings.map((x,i)=><div className="bar-row" key={x.date}><span>{x.label.slice(0,6)}</span><div><i style={{width:`${x.actual/5*100}%`}}/><b style={{width:`${(decisions[i]?.resultingRate||0)/5*100}%`}}/></div><em>{decisions[i]?.resultingRate.toFixed(2)||"—"}%</em></div>)}</div><div className="legend"><span><i className="actual"/>Observed FOMC</span><span><i className="player"/>Your simulated path</span></div></div><div className="scorecard"><div className="section-title"><span>02</span> LOSS DECOMPOSITION</div><strong>{decisions.reduce((a,d)=>a+d.loss,0).toFixed(2)}</strong><small>DISCOUNTED MODEL LOSS · LOWER IS BETTER</small><p>Quadratic loss combines normalized inflation, output and unemployment gaps. It is a decision aid, not an objective ranking of policymakers.</p><button className="primary" onClick={()=>{reset();setScreen("room")}}>RUN AGAIN</button></div></div><div className="journal">{decisions.map((d,i)=><article key={d.date}><header><span>{meetings[i].label}</span><b>{d.change>0?`+${d.change}`:d.change===0?"HOLD":d.change} BP · {d.guidance}</b></header><p>{d.memo||"No memo recorded."}</p><footer>SIMULATED RATE {d.resultingRate.toFixed(3)}% · PERIOD LOSS {d.loss.toFixed(2)}</footer></article>)}</div></section>}
  {screen==="method"&&<section className="method"><div className="eyebrow">MODEL CARD · VERSION 1.0</div><h1>TRANSPARENT BY DESIGN</h1><p className="lead">A calibrated semi-structural counterfactual simulation. Not a structural oracle.</p><div className="method-grid"><article><span>01 / INFORMATION</span><h2>No hindsight</h2><p>Each packet has an observation period, release date and decision cutoff. A packet fails validation when any release date exceeds its cutoff. Revised data are excluded from normal play.</p></article><article><span>02 / TRANSMISSION</span><h2>Delayed effects</h2><p>Policy first affects real rates and financial conditions, then output and unemployment, then inflation. Effects build over several quarters; no instantaneous disinflation is imposed.</p></article><article><span>03 / UNCERTAINTY</span><h2>Seeded Monte Carlo</h2><p>Each decision generates 1,000 reproducible paths. The interface reports medians and 10th–90th percentiles. Probabilities are model-conditioned frequencies.</p></article><article><span>04 / EXPECTATIONS</span><h2>Credibility matters</h2><p>Expected inflation blends the target and recent inflation. Credibility weakens with persistent misses; communication shifts expectations only through a bounded coefficient.</p></article></div><div className="equation"><span>STATE TRANSITION</span><code>x(t+1) = A·x(t) + B(L)·policy(t) + Γ·shock(t+1)</code><p>State: inflation, expected inflation, output gap, unemployment, policy rate, credit, financial stress, credibility.</p></div><div className="sources"><h2>PRIMARY SOURCES</h2><a href="https://fred.stlouisfed.org/docs/api/fred/series_observations.html">FRED / ALFRED API documentation ↗</a><a href="https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm">Federal Reserve FOMC calendars ↗</a><a href="https://www.bls.gov/bls/news-release/cpi.htm">BLS CPI release archive ↗</a><p>See repository methodology, calibration table, data registry and limitations for the full audit trail.</p></div></section>}
 </main>
}
