function kernel(months,peak,magnitude){const raw=Array.from({length:months},(_,h)=>h===0?0:(h/peak)*Math.exp(1-h/peak));const scale=Math.max(...raw);return raw.map(x=>magnitude*x/scale)}
function response(spec,deviationBp,name){const c=spec.transmission[name],k=kernel(spec.transmission.months,c.peak_month,c.magnitude_per_100bp);return deviationBp.map((_,t)=>deviationBp.slice(0,t+1).reduce((a,d,j)=>a+d/100*k[t-j],0))}
export function deterministicUnified(spec,input,months=input.playerPath.length,shockSequence=[]){
 if(input.monthlyPriceChanges.length!==12)throw new Error("historical scenarios require exactly 12 monthly PCE flows");
 if(input.playerPath.length!==input.baselinePath.length)throw new Error("policy paths must share a monthly clock");
 const changes=[...input.monthlyPriceChanges],dev=input.playerPath.map((x,i)=>(x-input.baselinePath[i])*100),ri=response(spec,dev,"inflation"),ro=response(spec,dev,"output"),ru=response(spec,dev,"unemployment"),rs=response(spec,dev,"financial_conditions");let y=input.output,u=input.unemployment,s=input.stress;
 return input.playerPath.slice(0,months).map((rate,t)=>{const shock=shockSequence[t]||{inflation:0,output:0,unemployment:0,financial_conditions:0};const flow=spec.inflation.intercept+spec.inflation.lag_coefficients.reduce((a,b,j)=>a+b*changes[changes.length-j-1],0)+ri[t]/12+shock.inflation;changes.push(flow);y=spec.state.output_persistence*y+ro[t]+shock.output;u=4+spec.state.unemployment_persistence*(u-4)+ru[t]+shock.unemployment;s=spec.state.stress_persistence*s+rs[t]+shock.financial_conditions;return{month:t+1,monthly_price_change:flow,pce_yoy:changes.slice(-12).reduce((a,b)=>a+b,0),output_gap:y,unemployment:Math.max(2.5,Math.min(12,u)),financial_stress:Math.max(0,Math.min(2,s)),policy_rate:rate,policy_deviation_bp:dev[t],policy_inflation_contribution:ri[t],policy_output_contribution:ro[t]}})
}
function rng(seed){return()=>{let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function normal(r){const u=Math.max(r(),1e-9),v=r();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
export function simulateUnified(spec,input,paths=1000){const r=rng(input.seed),playerPath=Array(24).fill(input.rate),baselinePath=Array(24).fill(input.baseline),series=Array.from({length:paths},()=>deterministicUnified(spec,{...input,playerPath,baselinePath},24,Array.from({length:24},()=>({inflation:normal(r)*.09,output:normal(r)*.08,unemployment:normal(r)*.04,financial_conditions:0}))));const q=(h,k,p)=>series.map(x=>x[h][k]).sort((a,b)=>a-b)[Math.floor((paths-1)*p)];return [2,5,8,11,14,17,20,23].map(h=>({h,pi:q(h,"pce_yoy",.5),lo:q(h,"pce_yoy",.1),hi:q(h,"pce_yoy",.9),y:q(h,"output_gap",.5),u:q(h,"unemployment",.5)}))}
